# Generated by Django 5.0.4 on 2024-09-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrcid', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('Verified', 'Verified'), ('Registered', 'Registered'), ('Unverified', 'Unverified')], max_length=10)),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('dateofbirth', models.DateField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNo', models.CharField(max_length=15)),
                ('aeNo', models.CharField(max_length=15)),
                ('lineMinistry', models.CharField(max_length=30)),
                ('institution', models.CharField(max_length=50)),
                ('institutionAcronymn', models.CharField(max_length=6)),
                ('station', models.CharField(max_length=15)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eip.identity')),
            ],
        ),
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStampNo', models.CharField(max_length=15)),
                ('timeVerified', models.CharField(max_length=15)),
                ('userVerifiedBy', models.CharField(max_length=15)),
                ('isVerified', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('employeeNo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eip.employee')),
            ],
        ),
    ]
