version: "4"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8001"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    environment:
      - DB_HOST=db-flights
      - DB_NAME=flightsdb
      - DB_USER=superuser
      - DB_PASS=Oceanic@815
    depends_on:
      - db-flights

  db-flights:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=flightsdb
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=Oceanic@815

volumes:
  local_pgdata:
  dev-static-data: